export const styleNoActive = {
  border: '1px solid #3D3D3D',
  borderRadius: '0.5rem',
  color: '#828585',
  fontSize: '14px',
  width: '5.25rem',
};

export const styleActive = {
  background: '#DBDBDB',
  borderRadius: '0.5rem',
  color: '#242424',
  fontSize: '14px',
  transition: 'all 0.5s',
  width: '5.25rem',
};

export const grading: {
  [i: string]: {
    value: string;
  }[];
} = {
  BBCE: [
    { value: 'PR 1' },
    { value: 'FR 1.5' },
    { value: 'Good 2' },
    { value: 'Good+2.5' },
    { value: 'VG 3' },
    { value: 'VG+ 3.5' },
    { value: 'VG-EX 4' },
    { value: 'VG-EX+ 4.5' },
    { value: 'EX 5' },
    { value: 'EX+ 5.5' },
    { value: 'EX-MT 6' },
    { value: 'EX-MT+ 6.5' },
    { value: 'NM 7' },
    { value: 'NM+ 7.5' },
    { value: 'NM-MT 8' },
    { value: 'NM-MT+ 8.5' },
    { value: 'MINT 9' },
    { value: 'GEM-MT 10' },
  ],
  Beckett: [
    { value: 'BGS0' },
    { value: '1 Poor' },
    { value: '2-G' },
    { value: '2.5-G+' },
    { value: '3-VG' },
    { value: '3.5-VG+' },
    { value: '4-VG-EX' },
    { value: '4.5 VG-EX+' },
    { value: '5-EX' },
    { value: '5.5-EX +' },
    { value: '6-EX-NM' },
    { value: '6.5-EX-NM+' },
    { value: '7-Near Mint' },
    { value: '7.5-Near Mint +' },
    { value: '8-Near Mint-Mint' },
    { value: '8.5-Near Mint-Mint +' },
    { value: '9-Mint' },
    { value: '9.5-Gem Mint' },
    { value: '10-Pristine' },
    { value: '10-Pristine Black Label' },
    { value: '10-Pristine Gold Label' },
  ],
  'CGC Trading Cards': [
    { value: 'Poor 1' },
    { value: 'Fair 1.5' },
    { value: 'Good 2' },
    { value: 'Good+ 2.5' },
    { value: 'Very Good 3' },
    { value: 'Very Good+ 3.5' },
    { value: 'VG/Ex 4' },
    { value: 'VG/Ex+ 4.5' },
    { value: 'Excellent 5' },
    { value: 'Excellent+ 5.5' },
    { value: 'Ex/NM 6' },
    { value: 'Ex/NM+ 6.5' },
    { value: 'NM 7' },
    { value: 'NM+ 7.5' },
    { value: 'NM/Mint 8' },
    { value: 'NM/Mint+ 8.5' },
    { value: 'Mint 9' },
    { value: 'Gem Mint 9.5' },
    { value: 'Pristine 10' },
    { value: 'Perfect 10' },
  ],
  CGS: [
    { value: 'Poor 1' },
    { value: 'Fair 1.5' },
    { value: 'Good 2' },
    { value: 'Good+ 2.5' },
    { value: 'Very Good 3' },
    { value: 'Very Good+ 3.5' },
    { value: 'VG/Ex 4' },
    { value: 'VG/Ex+ 4.5' },
    { value: 'Excellent 5' },
    { value: 'Excellent+ 5.5' },
    { value: 'Ex/NM 6' },
    { value: 'Ex/NM+ 6.5' },
    { value: 'NM 7' },
    { value: 'NM+ 7.5' },
    { value: 'NM/Mint 8' },
    { value: 'NM/Mint+ 8.5' },
    { value: 'Mint 9' },
    { value: 'Gem Mint 9.5' },
    { value: 'Pristine 10' },
    { value: 'Perfect 10' },
  ],
  CSG: [
    { value: 'Poor 1' },
    { value: 'Fair 1.5' },
    { value: 'Good 2' },
    { value: 'Good+ 2.5' },
    { value: 'Very Good 3' },
    { value: 'Very Good+ 3.5' },
    { value: 'VG/Ex 4' },
    { value: 'VG/Ex+ 4.5' },
    { value: 'Excellent 5' },
    { value: 'Excellent+ 5.5' },
    { value: 'Ex/NM 6' },
    { value: 'Ex/NM+ 6.5' },
    { value: 'NM 7' },
    { value: 'NM+ 7.5' },
    { value: 'NM/Mint 8' },
    { value: 'NM/Mint+ 8.5' },
    { value: 'Mint 9' },
    { value: 'Gem Mint 9.5' },
    { value: 'Pristine 10' },
    { value: 'Perfect 10' },
  ],
  KSA: [
    { value: 'A Authentic' },
    { value: '1 FP' },
    { value: '2 G' },
    { value: '3 VG' },
    { value: '4 VGE' },
    { value: '5 EX' },
    { value: '6 ENM' },
    { value: '6.5 ENM+' },
    { value: '7 NM' },
    { value: '7.5' },
    { value: '8 NMM' },
    { value: '8.5 NMM+' },
    { value: '9 Mint' },
    { value: '9.5 NGM' },
    { value: '10 Gem Mint' },
    { value: 'Authentic - Trimmed' },
    { value: 'Authentic - Coloured' },
  ],
  NGC: [],
  PCGS: [],
  PSA: [
    { value: 'PR 1' },
    { value: 'FR 1.5' },
    { value: 'Good 2' },
    { value: 'Good+2.5' },
    { value: 'VG 3' },
    { value: 'VG+ 3.5' },
    { value: 'VG-EX 4' },
    { value: 'VG-EX+ 4.5' },
    { value: 'EX 5' },
    { value: 'EX+ 5.5' },
    { value: 'EX-MT 6' },
    { value: 'EX-MT+ 6.5' },
    { value: 'NM 7' },
    { value: 'NM+ 7.5' },
    { value: 'NM-MT 8' },
    { value: 'NM-MT+ 8.5' },
    { value: 'MINT 9' },
    { value: 'GEM-MT 10' },
  ],
  'PSA/DNA': [
    { value: 'PR 1' },
    { value: 'FR 1.5' },
    { value: 'Good 2' },
    { value: 'Good+2.5' },
    { value: 'VG 3' },
    { value: 'VG+ 3.5' },
    { value: 'VG-EX 4' },
    { value: 'VG-EX+ 4.5' },
    { value: 'EX 5' },
    { value: 'EX+ 5.5' },
    { value: 'EX-MT 6' },
    { value: 'EX-MT+ 6.5' },
    { value: 'NM 7' },
    { value: 'NM+ 7.5' },
    { value: 'NM-MT 8' },
    { value: 'NM-MT+ 8.5' },
    { value: 'MINT 9' },
    { value: 'GEM-MT 10' },
  ],
  'Rare Edition': [
    { value: 'PR 1' },
    { value: 'FR 1.5' },
    { value: 'Good 2' },
    { value: 'Good+2.5' },
    { value: 'VG 3' },
    { value: 'VG+ 3.5' },
    { value: 'VG-EX 4' },
    { value: 'VG-EX+ 4.5' },
    { value: 'EX 5' },
    { value: 'EX+ 5.5' },
    { value: 'EX-MT 6' },
    { value: 'EX-MT+ 6.5' },
    { value: 'NM 7' },
    { value: 'NM+ 7.5' },
    { value: 'NM-MT 8' },
    { value: 'NM-MT+ 8.5' },
    { value: 'MINT 9' },
    { value: 'GEM-MT 10' },
  ],
  SGC: [
    { value: '1 POOR' },
    { value: '1.5 FAIR' },
    { value: '2 GOOD' },
    { value: '2.5 GOOD+' },
    { value: '3 VG' },
    { value: '3.5 VG+' },
    { value: '4 VG/EX' },
    { value: '4.5 VG/EX+' },
    { value: '5 EX' },
    { value: '5.5 EX+' },
    { value: '6 EX/NM' },
    { value: '6.5 EX/NM+' },
    { value: '7 NRMT' },
    { value: '7.5 NM+' },
    { value: '8 NM/MT' },
    { value: '8.5 NM/MT+' },
    { value: '9 MINT' },
    { value: '9.5 MINT+' },
    { value: '10 GM GEM' },
    { value: '10 PRI' },
  ],
  Steiner: [],
  UDA: [],
};
